language: perl
perl:
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  - LIBVER=1.7.0
  - LIBVER=1.6.0
  - LIBVER=1.5.0
  - LIBVER=1.4.3
  - LIBVER=1.2.4

install:
  - perl .travis/install-libssh2.pl $LIBVER
  - cpanm Module::Install::CheckLib ExtUtils::Constant;

script:
  - perl Makefile.PL lib=libssh2/lib inc=libssh2/include ldargs=-Wl,-rpath=libssh2/lib && make test
