language: perl
perl:
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"

env:
  - LIBVER=git
  - LIBVER=1.8.1
  - LIBVER=1.8.0
  - LIBVER=1.7.0
  - LIBVER=1.6.0

install:
  - perl .travis/install-libssh2.pl $LIBVER
  - cpanm Module::Install Module::Install::CheckLib ExtUtils::Constant;

script:
  - perl Makefile.PL lib=libssh2/lib inc=libssh2/include ldargs=-Wl,-rpath=libssh2/lib && make test
